version: '3.2'
services:
  redis:
    build:
      context: ./
      dockerfile: ./Dockerfiles/redis
    ports:
      - "6379:6379"
  server:
    build:
      context: ./
      dockerfile: ./Dockerfiles/server
    volumes:
      - ./files/server:/etc/sensu/conf.d
      - ./files/transport.json:/etc/sensu/conf.d/transport.json
  api:
    build:
      context: ./
      dockerfile: ./Dockerfiles/api
    ports:
      - "4567:4567"
    volumes:
      - ./files/api:/etc/sensu/conf.d
      - ./files/transport.json:/etc/sensu/conf.d/transport.json
  client:
    build:
      context: ./
      dockerfile: ./Dockerfiles/client
    volumes:
      - ./files/client:/etc/sensu/conf.d
      - ./files/transport.json:/etc/sensu/conf.d/transport.json
  uchiwa:
    build:
      context: ./
      dockerfile: ./Dockerfiles/uchiwa
    ports:
      - "3000:3000"
    volumes:
      - ./files/uchiwa/uchiwa.json:/etc/sensu/uchiwa.json
